server:
  port: 10010
logging:
  level:
    root: info
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 400000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximumPoolSize: 15
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.107.79.3:3306/iadmin?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  # redis 配置
  redis:
    database: 10              # Redis数据库索引（默认为0）
    host: 127.0.0.1          # Redis服务器地址
    password: 123456         # Redis服务器连接密码（默认为空）
    port: 6379               # Redis服务器连接端口
    timeout: 5000            # 连接超时时间（毫秒）
    Lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8      # 连接池中的最大空闲连接
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0      # 连接池中的最小空闲连接

permission:
  noCheckUrl: /doc.html,/actuator/**,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf